# Generated by Django 5.0.4 on 2024-05-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathtask',
            name='created_at',
        ),
        migrations.AddField(
            model_name='mathtask',
            name='correct_answer',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
